"""Generate the Claude Code agent roster (.claude/agents/*.md, roster.json, docs/AGENT_ROSTER.md section) from goals/ [ADR-016].

One agent per committee role (goals/00..28), per build epic (goals/build/E01..E15), per gate (goals/gate_*) and one
for the Master Delivery Orchestrator (GOAL.md). The prompt text is copied verbatim from the goals file so the goals
directory stays the single source of truth; ``--check`` fails when the generated files drift from it.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path

FIRST_LINE = {1, 2, 3, 4, 9, 10, 11, 12, 13, 15, 16, 17, 18, 19, 25, 26, 27}
SECOND_LINE = {5, 6, 7, 8, 14, 24}
THIRD_LINE = {20, 21, 22, 23, 28}
TOOLS = "Read, Grep, Glob, Bash, Edit, Write"
LEDGERS = (
    "docs/SESSIONS/",
    "docs/RAID_LOG.md",
    "docs/DECISION_LOG.md",
    "docs/REQUIREMENTS_TRACEABILITY.md",
    "docs/AUDIT_EVIDENCE_INDEX.md",
    "docs/MISSING_ACTIONS.md",
    "docs/REPORTS/",
)
THIRD_LINE_LEDGERS = ("docs/SESSIONS/REVIEW_", "docs/GATE_REPORTS/", "docs/RAID_LOG.md")
# Owned paths that the prose in "# YOU OWN" does not spell out as paths (kept in sync with goals/NN_*.md by review).
EXTRA_OWNED: dict[int, tuple[str, ...]] = {
    0: (
        "docs/BACKLOG.md",
        "docs/DEFINITION_OF_DONE.md",
        ".claude/agents/",
        ".mcp.json",
        "docs/AGENT_ROSTER.md",
        "docs/INSTALLATION.md",
        "docs/PRODUCT_OWNER.md",
    ),
    3: ("docs/SEQUENCE_DIAGRAMS.md", "docs/MARKET_LAUNCH_CHECKLIST.md", "docs/BROKER_CERTIFICATIONS/"),
    4: ("docs/STRATEGY_CARDS/", "docs/DATA_DICTIONARY.md"),
    5: ("docs/MODEL_CARDS/", "docs/PROMPT_REGISTRY.md"),
    6: ("docs/RISK_POLICY.md", "docs/LIMIT_MATRIX.md"),
    7: ("docs/COMPLIANCE_MATRIX.md", "docs/JURISDICTION_MATRIX.md"),
    8: ("docs/JURISDICTION_MATRIX.md", "docs/COMPLIANCE_MATRIX.md", "docs/LEGAL/"),
    11: ("infra/", "docs/CAPACITY_MODEL.md", "docs/DR_PLAN.md"),
    13: ("security/",),
    14: ("mcp/policies/", "docs/MCP_TOOL_CATALOG.md"),
    15: ("services/", "libs/", "test/", "contracts/events/"),
    17: ("apps/web/", "apps/admin/", "contracts/api/"),
    19: ("observability/",),
    20: ("test/",),
    21: ("test/performance/",),
    22: ("docs/ACCESSIBILITY/",),
    23: ("docs/PENTEST/",),
    25: ("docs/VENDOR_ASSESSMENTS/", "docs/CAPACITY_MODEL.md"),
    27: ("docs/MARKET_LAUNCH_CHECKLIST.md", "docs/GTM/"),
    28: ("docs/GATE_REPORTS/",),
}
BUILD_COMMON = ("test/", "contracts/events/", "docs/TEST_CASES/", "docs/ADRs/") + LEDGERS
GATE_PATHS = (
    "docs/DECISION_LOG.md",
    "docs/RAID_LOG.md",
    "docs/RELEASE_CHECKLIST.md",
    "docs/AUDIT_EVIDENCE_INDEX.md",
    "docs/SESSIONS/",
    "docs/GATE_REPORTS/",
)
ORCHESTRATOR_PATHS = ("docs/", "goals/", "README.md", "CLAUDE.md")
_PATH_TOKEN = re.compile(
    r"(?<![\w./-])((?:docs|goals|services|libs|mcp|connectors|contracts|infra|observability|security|apps|scripts|test)/[\w./\-*]*|\.mcp\.json|\.claude/[\w./-]*)"
)
ROSTER_BEGIN, ROSTER_END = "<!-- roster:begin (generated by scripts/generate_agents.py) -->", "<!-- roster:end -->"


@dataclass(frozen=True)
class AgentSpec:
    name: str
    kind: str  # role | build | gate | orchestrator
    line: str
    title: str
    description: str
    prompt: str
    allowed_paths: tuple[str, ...]
    source: str

    def markdown(self) -> str:
        hook = f"python3 scripts/agent_guard.py --agent {self.name}"
        front = [
            "---",
            f"name: {self.name}",
            f"description: {self.description}",
            f"tools: {TOOLS}",
            "hooks:",
            "  PreToolUse:",
            '    - matcher: "Edit|Write|MultiEdit|NotebookEdit"',
            "      hooks:",
            "        - type: command",
            f'          command: "{hook}"',
            "---",
        ]
        body = [
            f"<!-- generated from {self.source} by scripts/generate_agents.py; edit the source, not this file -->",
            "",
            self.prompt.rstrip(),
            "",
            "# WRITE SCOPE (enforced by scripts/agent_guard.py from .claude/agents/roster.json)",
            "You may edit only: " + ", ".join(self.allowed_paths) + ".",
            "Anything else is proposed in your session packet for the owning role. Protected paths still need the 2nd-line CODEOWNER.",
            "",
        ]
        return "\n".join(front + body)


def _prompt_block(text: str) -> tuple[str, str]:
    title = text.splitlines()[0].removeprefix("#").strip()
    title = re.sub(r"^/goal\s*[—-]\s*", "", title)
    m = re.search(r"```text\n(.*?)\n```", text, re.S)
    if not m:
        raise ValueError("no ```text prompt block")
    return title, m.group(1)


def _field(prompt: str, name: str) -> str:
    m = re.search(rf"^# {name}\n(.*?)(?=\n# |\Z)", prompt, re.S | re.M)
    return " ".join(m.group(1).split()) if m else ""


def _paths_in(text: str) -> tuple[str, ...]:
    out: list[str] = []
    for tok in _PATH_TOKEN.findall(text):
        tok = tok.rstrip(".,;:)").replace("*", "")
        if tok.endswith("/") or "." in tok.rsplit("/", 1)[-1]:
            pass
        else:
            tok += "/"
        if tok and tok not in out:
            out.append(tok)
    return tuple(out)


def _dedupe(paths: tuple[str, ...]) -> tuple[str, ...]:
    seen: list[str] = []
    for p in paths:
        if p not in seen:
            seen.append(p)
    return tuple(seen)


def _one_line(text: str, limit: int = 300) -> str:
    text = " ".join(text.split()).replace('"', "'")
    return text if len(text) <= limit else text[: limit - 1].rstrip() + "…"


def collect(root: Path) -> list[AgentSpec]:
    specs: list[AgentSpec] = []
    goal = root / "GOAL.md"
    title, prompt = _prompt_block(goal.read_text(encoding="utf-8"))
    specs.append(
        AgentSpec(
            name="delivery-orchestrator",
            kind="orchestrator",
            line="1st",
            title="Master Delivery Orchestrator",
            description=_one_line(
                "Master Delivery Orchestrator (1st line): coordinates the committee of role agents through discover-challenge-validate "
                "sessions, gates A-F, decision packs and external workflows; recommends, never approves. Use to plan a delivery cycle, "
                "run docs/PROJECT_EXECUTION_PLAN.md phases, or produce the weekly report."
            ),
            prompt=prompt,
            allowed_paths=ORCHESTRATOR_PATHS,
            source="GOAL.md",
        )
    )
    for f in sorted((root / "goals").glob("[0-9][0-9]_*.md")):
        n = int(f.name[:2])
        line = "1st" if n in FIRST_LINE or n == 0 else "2nd" if n in SECOND_LINE else "3rd"
        title, prompt = _prompt_block(f.read_text(encoding="utf-8"))
        owned = _paths_in(_field(prompt, "YOU OWN")) + EXTRA_OWNED.get(n, ())
        ledgers = THIRD_LINE_LEDGERS if line == "3rd" else LEDGERS
        name = f.stem[3:].replace("_", "-")
        desc = f"{title} ({line} line). Mandate: {_field(prompt, 'MANDATE')} Owns: {_field(prompt, 'YOU OWN')} May not: {_field(prompt, 'YOU MAY NOT')}"
        specs.append(
            AgentSpec(
                name=name,
                kind="role",
                line=line,
                title=title,
                description=_one_line(desc),
                prompt=prompt,
                allowed_paths=_dedupe(owned + ledgers),
                source=f.relative_to(root).as_posix(),
            )
        )
    for f in sorted((root / "goals" / "build").glob("E[0-9][0-9]_*.md")):
        title, prompt = _prompt_block(f.read_text(encoding="utf-8"))
        epic = f.name[:3].lower()
        owned = _paths_in(_field(prompt, "CODE AND ARTEFACT PATHS"))
        desc = f"{title} (1st line build agent). Scope: {_field(prompt, 'SCOPE OF THE EPIC (docs/BACKLOG.md)')} Tests: {_field(prompt, 'TEST IDS (docs/TEST_CASES/; evidence generated by `make evidence`)')}"
        specs.append(
            AgentSpec(
                name=f"build-{epic}",
                kind="build",
                line="1st",
                title=title,
                description=_one_line(desc),
                prompt=prompt,
                allowed_paths=_dedupe(owned + BUILD_COMMON),
                source=f.relative_to(root).as_posix(),
            )
        )
    for f in sorted((root / "goals").glob("gate_*.md")):
        title, prompt = _prompt_block(f.read_text(encoding="utf-8"))
        letter = f.name.split("_")[1].lower()
        desc = f"{title} convening agent: the Program Orchestrator presents, approving bodies decide, Independent Validation may veto. Exit evidence: {_field(prompt, 'EXIT EVIDENCE REQUIRED')} Approving bodies: {_field(prompt, 'APPROVING BODIES')}"
        specs.append(
            AgentSpec(
                name=f"gate-{letter}",
                kind="gate",
                line="governance",
                title=title,
                description=_one_line(desc),
                prompt=prompt,
                allowed_paths=GATE_PATHS,
                source=f.relative_to(root).as_posix(),
            )
        )
    return specs


def render(specs: list[AgentSpec]) -> dict[str, str]:
    files = {f".claude/agents/{s.name}.md": s.markdown() for s in specs}
    roster = {
        "generated_by": "scripts/generate_agents.py",
        "agents": {s.name: {"kind": s.kind, "line": s.line, "source": s.source, "allowed_paths": list(s.allowed_paths)} for s in specs},
    }
    files[".claude/agents/roster.json"] = json.dumps(roster, indent=2) + "\n"
    return files


def roster_table(specs: list[AgentSpec]) -> str:
    rows = ["| Agent | Kind | Line | Source prompt | Write scope |", "|---|---|---|---|---|"]
    for s in specs:
        rows.append(f"| `{s.name}` | {s.kind} | {s.line} | `{s.source}` | {', '.join(f'`{p}`' for p in s.allowed_paths)} |")
    return "\n".join(rows)


def write(root: Path, specs: list[AgentSpec]) -> list[str]:
    files = render(specs)
    agents_dir = root / ".claude" / "agents"
    agents_dir.mkdir(parents=True, exist_ok=True)
    for stale in agents_dir.glob("*"):
        if stale.is_file() and f".claude/agents/{stale.name}" not in files:
            stale.unlink()
    for rel, content in files.items():
        (root / rel).write_text(content, encoding="utf-8")
    doc = root / "docs" / "AGENT_ROSTER.md"
    if doc.exists():
        text = doc.read_text(encoding="utf-8")
        if ROSTER_BEGIN in text and ROSTER_END in text:
            head, rest = text.split(ROSTER_BEGIN, 1)
            _, tail = rest.split(ROSTER_END, 1)
            doc.write_text(head + ROSTER_BEGIN + "\n" + roster_table(specs) + "\n" + ROSTER_END + tail, encoding="utf-8")
    return sorted(files)


def check(root: Path, specs: list[AgentSpec]) -> list[str]:
    files = render(specs)
    problems: list[str] = []
    for rel, content in files.items():
        p = root / rel
        if not p.is_file():
            problems.append(f"missing {rel}")
        elif p.read_text(encoding="utf-8") != content:
            problems.append(f"drift in {rel}")
    for stale in (root / ".claude" / "agents").glob("*"):
        if stale.is_file() and f".claude/agents/{stale.name}" not in files:
            problems.append(f"stray file .claude/agents/{stale.name}")
    doc = root / "docs" / "AGENT_ROSTER.md"
    if doc.exists():
        text = doc.read_text(encoding="utf-8")
        if ROSTER_BEGIN in text and ROSTER_END in text:
            current = text.split(ROSTER_BEGIN, 1)[1].split(ROSTER_END, 1)[0].strip()
            if current != roster_table(specs).strip():
                problems.append("drift in docs/AGENT_ROSTER.md roster table")
    return problems
